# Generated by Django 5.2.1 on 2025-05-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=120)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Phone Data',
                'verbose_name_plural': 'Phone Data',
            },
        ),
    ]
